name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  create-recipes:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            cuda-version: "12.9"
          - os: ubuntu-latest
            cuda-version: "13.0"
          - os: ubuntu-latest
            cuda-version: "13.2"
          # Windows:
          # cuda <13.2 requires Visual Studio 2022, available on windows-2022 runner
          - os: windows-2022
            cuda-version: "12.9"
          - os: windows-2022
            cuda-version: "13.0"
          # cuda >=13.2 can run on windows-latest (Visual Studio 2026)
          - os: windows-latest
            cuda-version: "13.2"

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Conan
        uses: conan-io/setup-conan@v1

      - name: conan create
        run: conan create recipes/cuda-toolkit/${{ matrix.cuda-version }}
